=== Esheen/XML-XSD-XSLT-project/XML:XSD:XSLT/forecast.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
	targetNamespace="http://www.w3schools.com" 
	xmlns="http://www.w3schools.com" 
	elementFormDefault="qualified">
	<xs:complexType name="WeeksType">
		<xs:attribute name="week"
			type="xs:int"
			use="required"/>
		<xs:attribute name="weeklyActivity"
			type="xs:string"
			use="required"/>
		<xs:attribute name="BPForecast"
			type="xs:int"
			use="required"/>
		<xs:attribute name="IndForecast"
			type="xs:int"
			use="required"/>
		<xs:attribute name="OrderQuantity"
			type="xs:int"
			use="required"/>	
		<xs:attribute name="PromiseQuantity"
			type="xs:int"
			use="required"/>	
	</xs:complexType>
	<xs:complexType name="ItemType">
		<xs:sequence>
			<xs:element name="Weeks"
				maxOccurs="unbounded"
				type="WeeksType"/>
		</xs:sequence>
		<xs:attribute name="item"
			type="xs:string"
			use="required"/>
		<xs:attribute name="itemPopularity"
			type="xs:string"
			use="required"/>
		<xs:attribute name="avgOrder"
			type="xs:int"
			use="required"/>
	</xs:complexType>
	<xs:complexType name="ForecastingType">
		<xs:sequence>
			<xs:element name="Item"
				maxOccurs="unbounded"
				type="ItemType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="Forecasting"
		type="ForecastingType"/>
</xs:schema>

=== Esheen/XML-XSD-XSLT-project/XML:XSD:XSLT/Forecasting.xml
<?xml version="1.0" encoding="utf-8" ?>
<?xml-stylesheet type="text/xsl" href="forecast.xslt" ?>
<Forecasting xmlns="http://www.w3schools.com" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://w3schools.com forecast.xsd">
	<Item item="fishbone" itemPopularity="best reviewed" avgOrder="5">
		<Weeks week="1" weeklyActivity="replenish" BPForecast="6" IndForecast="5" OrderQuantity="30" PromiseQuantity="5" />
		<Weeks week="2" weeklyActivity="sales" BPForecast="8" IndForecast="8" OrderQuantity="30" PromiseQuantity="8" />
		<Weeks week="3" weeklyActivity="newBrand" BPForecast="8" IndForecast="7" OrderQuantity="15" PromiseQuantity="5" />
	</Item>
	<Item item="catChewies" itemPopularity="most popular" avgOrder="4">
		<Weeks week="1" weeklyActivity="replenish" BPForecast="6" IndForecast="5" OrderQuantity="20" PromiseQuantity="5" />
		<Weeks week="2" weeklyActivity="sales" BPForecast="8" IndForecast="8" OrderQuantity="30" PromiseQuantity="8" />
		<Weeks week="3" weeklyActivity="newBrand" BPForecast="8" IndForecast="7" OrderQuantity="20" PromiseQuantity="5" />
	</Item>
</Forecasting>
